#!/usr/bin/env bash
exec ./run \
    -job_id wordcount_transientresource \
    -user_main edu.useoul.spl.nemo.app.WordCount \
    -optimization_policy edu.useoul.spl.nemo.policy.TransientResourcePolicy
