#!/usr/bin/env bash
exec ./run \
    -job_id als_transientresource \
    -user_main edu.useoul.spl.nemo.app.AlternatingLeastSquare \
    -optimization_policy edu.useoul.spl.nemo.policy.TransientResourcePolicy
